lm = None #LocaleManager
media_manager = None #MediaManager
asset_manager = None #AssetManager
page_manager = None #PageManager
settings_manager = None #SettingsManager
app = None #App
deck_manager = None #DeckManager
plugin_manager = None #PluginManager
video_extensions = ["mp4", "mov", "MP4", "MOV", "mkv", "MKV", "webm", "WEBM", "gif", "GIF"]
image_extensions = ["png", "jpg", "jpeg"]