[Icon Theme]
Name=Hicolor
Comment=Icons bundled with StreamController
Directories=48x48/apps,512x512/apps,scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/mimetypes,scalable/places,scalable/status

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[512x512/apps]
Size=512
Context=Applications
Type=Fixed

[scalable/actions]
Size=16
MinSize=8
MaxSize=512
Context=Actions
Type=Scalable

[scalable/apps]
Size=16
MinSize=8
MaxSize=512
Context=Applications
Type=Scalable

[scalable/categories]
Size=16
MinSize=8
MaxSize=512
Context=Categories
Type=Scalable

[scalable/devices]
Size=16
MinSize=8
MaxSize=512
Context=Devices
Type=Scalable

[scalable/mimetypes]
Size=16
MinSize=8
MaxSize=512
Context=MimeTypes
Type=Scalable

[scalable/places]
Size=16
MinSize=8
MaxSize=512
Context=Places
Type=Scalable

[scalable/status]
Size=16
MinSize=8
MaxSize=512
Context=Status
Type=Scalable
