name: Release
on:
  workflow_dispatch:
  push:
    - main
    - beta
    - alpha

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semrel.outputs.version }}

    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        name: Release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
